{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zyp.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 12237,
          "sha512": "aa6b7e2d6c5050eb6ca7941d5d13d56beae9e082667a2c26b7f4a2e699d20bf48000e79daf90d7451d78c8842d8223f33414e9d92f7731c78cb8f4d7826cfc4e",
          "sha256": "bfba222cbafc3eba36c36adf17457f0d1349009d338837c6147fd627cd963f4c",
          "sha1": "b3241945bbb2af2b932dad4e1357f4b3f9a8424c",
          "md5": "2d8f9645ce9e4e454bbcae55466c1094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 12237,
          "sha512": "aa6b7e2d6c5050eb6ca7941d5d13d56beae9e082667a2c26b7f4a2e699d20bf48000e79daf90d7451d78c8842d8223f33414e9d92f7731c78cb8f4d7826cfc4e",
          "sha256": "bfba222cbafc3eba36c36adf17457f0d1349009d338837c6147fd627cd963f4c",
          "sha1": "b3241945bbb2af2b932dad4e1357f4b3f9a8424c",
          "md5": "2d8f9645ce9e4e454bbcae55466c1094"
        }
      ]
    }
  ]
}
